version: '2'
services:
    souvenir-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/Souvenir/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=Souvenir
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
